apiVersion: v1
kind: Namespace
metadata:
  name: exp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-renderer
  namespace: exp
  labels:
    app: pdf-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-renderer
  template:
    metadata:
      labels:
        app: pdf-renderer
        role: pdf-renderer
    spec:
      containers:
        - name: pdf-renderer
          image: registry:5000/pdfrender:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "1024Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pdf-renderer
  namespace: exp
  labels:
    run: pdf-renderer
    role: pdf-renderer
spec:
  ports:
    - port: 8080
      name: service
      protocol: TCP
    - port: 8081
      name: test
      protocol: TCP
  selector:
    run: pdf-renderer
